# Site settings
title: Wow
email: youremailaddress@gmail.com
description: Some description
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Logo settings
logo-placeholder: images/logo.svg

# Build settings
markdown: kramdown
sass:
  sass_dir: assets/css
  style: compressed

# Layout settings
home-link-in-menu: yes

# Collections
collections:
  years:
    output: true
    permalink: /:title
  years2:
    output: true
    permalink: /:title
  speakers:
    output: true
    permalink: /speakers/:path/
  sections:
    output: false

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      categories: ""
      tags: []
      featured-image: ""
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      featured-image: ""
  - scope:
      path: ""
      type: years
    values:
      layout: years
      title: "The Annual SE Conference 201X"
      registration: false
      call-for-speakers: true
      main-color: "#444"
      gradient-colors: []
      featured-image: ""
      sections: []
      speakers: []
      speaker-section-index: 0
  - scope:
      path: ""
      type: years2
    values:
      layout: years2
      featured-image: ""
      title: "The Annual SE Conference 201X"
      registration: "coming soon"
      past: false
      registrationOptions: []
      main-color: "#444"
      gradient-colors: []
      panels: []
  - scope:
      path: ""
      type: sections
    values:
      layout: sections
      title: "Section Title"
      background: ""
      tabs: []
      isSpeakers: false
      speakers: []
  - scope:
      path: ""
      type: speakers
    values:
      layout: speakers
      name: Example Name
      short_bio: A little bio
      pic: /images/pic04.jpg
